# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Sun Oct 20 14:14:11 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.verticalLayout.addWidget(self.image_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backward_small = QtWidgets.QPushButton(self.centralwidget)
        self.backward_small.setObjectName("backward_small")
        self.horizontalLayout_2.addWidget(self.backward_small)
        self.backward_big = QtWidgets.QPushButton(self.centralwidget)
        self.backward_big.setObjectName("backward_big")
        self.horizontalLayout_2.addWidget(self.backward_big)
        self.select = QtWidgets.QPushButton(self.centralwidget)
        self.select.setObjectName("select")
        self.horizontalLayout_2.addWidget(self.select)
        self.forward_big = QtWidgets.QPushButton(self.centralwidget)
        self.forward_big.setObjectName("forward_big")
        self.horizontalLayout_2.addWidget(self.forward_big)
        self.forward_small = QtWidgets.QPushButton(self.centralwidget)
        self.forward_small.setObjectName("forward_small")
        self.horizontalLayout_2.addWidget(self.forward_small)
        self.step_spin = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_spin.sizePolicy().hasHeightForWidth())
        self.step_spin.setSizePolicy(sizePolicy)
        self.step_spin.setSpecialValueText("")
        self.step_spin.setMinimum(1)
        self.step_spin.setMaximum(999)
        self.step_spin.setProperty("value", 10)
        self.step_spin.setObjectName("step_spin")
        self.horizontalLayout_2.addWidget(self.step_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        self.menuOpen_Folder = QtWidgets.QMenu(self.menubar)
        self.menuOpen_Folder.setObjectName("menuOpen_Folder")
        self.menuMove_selected = QtWidgets.QMenu(self.menubar)
        self.menuMove_selected.setObjectName("menuMove_selected")
        self.menuRemove_unselected = QtWidgets.QMenu(self.menubar)
        self.menuRemove_unselected.setObjectName("menuRemove_unselected")
        MainWindow.setMenuBar(self.menubar)
        self.actionMove_Selected = QtWidgets.QAction(MainWindow)
        self.actionMove_Selected.setObjectName("actionMove_Selected")
        self.actionCopy_Selected = QtWidgets.QAction(MainWindow)
        self.actionCopy_Selected.setObjectName("actionCopy_Selected")
        self.actionRemove_Unselected = QtWidgets.QAction(MainWindow)
        self.actionRemove_Unselected.setObjectName("actionRemove_Unselected")
        self.actionRemove_Selected = QtWidgets.QAction(MainWindow)
        self.actionRemove_Selected.setObjectName("actionRemove_Selected")
        self.actionCopy_Unselected = QtWidgets.QAction(MainWindow)
        self.actionCopy_Unselected.setObjectName("actionCopy_Unselected")
        self.actionMove_Unselected = QtWidgets.QAction(MainWindow)
        self.actionMove_Unselected.setObjectName("actionMove_Unselected")
        self.actionOpenFolder = QtWidgets.QAction(MainWindow)
        self.actionOpenFolder.setObjectName("actionOpenFolder")
        self.menuOpen_Folder.addAction(self.actionOpenFolder)
        self.menuMove_selected.addAction(self.actionMove_Selected)
        self.menuMove_selected.addAction(self.actionCopy_Selected)
        self.menuMove_selected.addAction(self.actionRemove_Selected)
        self.menuRemove_unselected.addAction(self.actionMove_Unselected)
        self.menuRemove_unselected.addAction(self.actionCopy_Unselected)
        self.menuRemove_unselected.addAction(self.actionRemove_Unselected)
        self.menubar.addAction(self.menuOpen_Folder.menuAction())
        self.menubar.addAction(self.menuMove_selected.menuAction())
        self.menubar.addAction(self.menuRemove_unselected.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.image_label.setText(QtWidgets.QApplication.translate("MainWindow", "Open a folder first..", None, -1))
        self.backward_small.setText(QtWidgets.QApplication.translate("MainWindow", "Forward -1", None, -1))
        self.backward_big.setText(QtWidgets.QApplication.translate("MainWindow", "Backward -10", None, -1))
        self.select.setText(QtWidgets.QApplication.translate("MainWindow", "Select", None, -1))
        self.forward_big.setText(QtWidgets.QApplication.translate("MainWindow", "Forward +10", None, -1))
        self.forward_small.setText(QtWidgets.QApplication.translate("MainWindow", "Forward +1", None, -1))
        self.step_spin.setSuffix(QtWidgets.QApplication.translate("MainWindow", " Steps", None, -1))
        self.step_spin.setPrefix(QtWidgets.QApplication.translate("MainWindow", " ", None, -1))
        self.menuOpen_Folder.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuMove_selected.setTitle(QtWidgets.QApplication.translate("MainWindow", "Selected", None, -1))
        self.menuRemove_unselected.setTitle(QtWidgets.QApplication.translate("MainWindow", "Unselected", None, -1))
        self.actionMove_Selected.setText(QtWidgets.QApplication.translate("MainWindow", "Move Selected", None, -1))
        self.actionCopy_Selected.setText(QtWidgets.QApplication.translate("MainWindow", "Copy Selected", None, -1))
        self.actionRemove_Unselected.setText(QtWidgets.QApplication.translate("MainWindow", "Remove Unselected", None, -1))
        self.actionRemove_Selected.setText(QtWidgets.QApplication.translate("MainWindow", "Remove Selected", None, -1))
        self.actionCopy_Unselected.setText(QtWidgets.QApplication.translate("MainWindow", "Copy Unselected", None, -1))
        self.actionMove_Unselected.setText(QtWidgets.QApplication.translate("MainWindow", "Move Unselected", None, -1))
        self.actionOpenFolder.setText(QtWidgets.QApplication.translate("MainWindow", "Open Folder", None, -1))

